version: 2
updates:
- directory: "/api"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target_branch: "master"
  package_manager: "python"
- directory: "/front"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target_branch: "master"
  package_manager: "javascript"
