version: 2
updates:
- package-ecosystem: pip
  directory: "/api"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target_branch: "api"
- package-ecosystem: npm
  directory: "/front"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target_branch: "api"
- package-ecosystem: pip
  directory: "/api"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target_branch: "master"
- package-ecosystem: npm
  directory: "/front"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target_branch: "master"
