repos:
    - repo: local
      hooks:
          - id: black
            name: black
            language: system
            entry: black --config=api/pyproject.toml
            types: [python]
            files: ^api/
          - id: flake8
            name: flake8
            language: system
            entry: flake8 --config=api/setup.cfg
            types: [python]
            files: ^api/
          - id: jslint
            name: jslint
            language: system
            entry: yarn lint
            types: [vue, javascript]
            files: ^front/